import os


TEMPORAL_HOST =os .getenv ("TEMPORAL_HOST","localhost:7233")
K8S_TASK_QUEUE ="k8s-monitor-queue"

OLLAMA_HOST =os .getenv ("OLLAMA_HOST","http://localhost:11434")
OLLAMA_MODEL =os .getenv ("OLLAMA_MODEL","qwen2.5-coder:3b")

K8S_DEFAULT_NAMESPACE =os .getenv ("K8S_DEFAULT_NAMESPACE","default")
K8S_ALL_NAMESPACES =os .getenv ("K8S_ALL_NAMESPACES","false").lower ()=="true"

POD_RESTART_THRESHOLD =int (os .getenv ("POD_RESTART_THRESHOLD","5"))

LIST_PODS_TIMEOUT =10
HEALTH_CHECK_TIMEOUT =15
LOG_RETRIEVAL_TIMEOUT =10
RESTART_POD_TIMEOUT =30
DEPLOYMENT_CHECK_TIMEOUT =10
AI_ORCHESTRATOR_TIMEOUT =20
